function escape(value = '') {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}
function layout(title, user, body, notice = '') {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · LyricalSource CMS</title>
  <style>body{font:16px system-ui,sans-serif;background:#101017;color:#f5f5fa;margin:0}header{display:flex;gap:1.5rem;align-items:center;padding:1rem 2rem;background:#1c1b29;flex-wrap:wrap}header a{color:#ddd}main{max-width:1050px;margin:2rem auto;padding:0 1rem}a{color:#c8b5ff}h1{font-size:2rem}input,textarea,select,button{font:inherit}input,textarea,select{box-sizing:border-box;width:100%;padding:.7rem;background:#20202c;border:1px solid #4b4b59;color:white;border-radius:7px}textarea{min-height:220px}label{display:block;margin:1rem 0}.short{max-width:400px}.row{display:flex;gap:1rem;flex-wrap:wrap;align-items:center}.row>*{flex:1}.card{background:#1b1b25;border:1px solid #373744;padding:1.25rem;margin:1rem 0;border-radius:10px}button,.button{background:#8059d9;color:white;border:0;border-radius:7px;padding:.7rem 1rem;cursor:pointer;text-decoration:none;display:inline-block}button.secondary{background:#3a3a49}.danger{color:#ffb6b6}.notice{background:#2b3450;padding:1rem;border-radius:8px}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:.7rem;border-bottom:1px solid #333}small{color:#aaa}.editor{min-height:340px;background:#20202c;border:1px solid #4b4b59;border-radius:7px;padding:1rem;line-height:1.6}.editor img{max-width:100%}.toolbar button{padding:.4rem .7rem;margin:.2rem;background:#444}.preview{background:#fff;color:#111;padding:2rem;border-radius:8px;line-height:1.7}.preview img{max-width:100%}</style></head><body>
  <header><strong>LyricalSource CMS</strong>${user ? `<a href="/">Articles</a>${['superuser','owner'].includes(user.role) ? '<a href="/team">Team</a>' : ''}<a href="/account">Account</a><span>${escape(user.email)} (${escape(user.role)})</span><form method="post" action="/logout"><button class="secondary">Log out</button></form>` : ''}</header>
  <main>${notice ? `<p class="notice">${escape(notice)}</p>` : ''}${body}</main></body></html>`;
}
module.exports = { escape, layout };
