const avatars = ['sage', 'coral', 'indigo', 'gold', 'rose', 'teal'];
const cmsPath = new URL(process.env.CMS_BASE_URL || 'http://127.0.0.1:3100').pathname.replace(/\/$/, '');
const cmsUrl = value => value.startsWith('/') && !value.startsWith('//') ? cmsPath + value : value;
function escape(value = '') {
  return String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]);
}
function layout(title, user, body, notice = '') {
  const showRole = user && (user.name || user.email).trim().toLowerCase() !== user.role.toLowerCase();
  const paths = { Articles: '<path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8Z"/><path d="M14 2v6h6M8 12h8M8 16h6"/>', Songs: '<path d="M9 18V5l12-2v13M9 9l12-2"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/>', Team: '<path d="M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87"/><circle cx="9" cy="7" r="4"/><path d="M16 3a4 4 0 0 1 0 8"/>', Account: '<circle cx="12" cy="8" r="4"/><path d="M4 22v-3a8 8 0 0 1 16 0v3"/>', 'Staff login': '<path d="M9 5H4v14h5M14 8l4 4-4 4M8 12h10"/>' };
  const nav = (href, label, active) => `<a href="${href}" ${active ? 'aria-current="page"' : ''}><svg width="21" height="21" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${paths[label] || (label === 'Albums' ? '<circle cx="12" cy="12" r="9"/><circle cx="12" cy="12" r="3"/>' : label === 'Playlists' ? '<path d="M4 6h16M4 11h12M4 16h8M18 14v7l5-3.5Z"/>' : '')}</svg><span>${label}</span></a>`;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#11191b"><meta name="robots" content="noindex,nofollow"><title>${escape(title)} · LyricalSource CMS</title>
  <link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icons/icon-192.png"><link rel="apple-touch-icon" href="/icons/icon-192.png"><link rel="stylesheet" href="/app.css"><script defer src="/app.js"></script></head><body>
  <a class="skip" href="#content">Skip to content</a><div class="shell"><aside class="sidebar"><a class="brand" href="/"><span class="brand-mark">L</span><span>LyricalSource<small>EDITORIAL STUDIO</small></span></a>
  <p class="nav-label">WORKSPACE</p><nav aria-label="Main navigation">${user ? `${nav('/', 'Articles', ['Articles','Edit article','New article','Preview','Article error'].includes(title))}${nav('/albums', 'Albums', ['Albums','Edit album'].includes(title))}${nav('/playlists', 'Playlists', ['Playlists','New playlist','Edit playlist'].includes(title))}${['superuser','owner','editor'].includes(user.role) ? nav('/songs','Songs',['Songs','Edit song'].includes(title)) : ''}${['superuser','owner'].includes(user.role) ? nav('/team','Team',title === 'Team') : ''}` : nav('/login','Staff login',title === 'Login')}</nav>
  <div class="sidebar-bottom"><span class="status-dot"></span> One team. One workspace.${user ? `<details class="profile-menu" data-profile-menu><summary class="profile-trigger" aria-label="Profile options for ${escape(user.name || user.email)}"><img class="profile-avatar" src="/avatars/${avatars[(Math.max(1, Number(user.id) || 1) - 1) % avatars.length]}.svg" alt=""><span class="profile-name">${escape(user.name || user.email)}${showRole ? `<small>${escape(user.role)}</small>` : ''}</span><span class="profile-chevron" aria-hidden="true">⌃</span></summary><div class="profile-options"><p class="profile-email">${escape(user.email)}</p><a href="/account">Account settings</a><form method="post" action="/logout"><button class="profile-logout">Log out</button></form></div></details>` : ''}</div></aside>
  <div class="workspace"><header class="topbar">${user ? '<form class="global-search" action="/" method="get" role="search"><svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" aria-hidden="true"><circle cx="10" cy="10" r="6"/><path d="m15 15 5 5"/></svg><label class="sr-only" for="workspace-search">Search articles</label><input id="workspace-search" type="search" name="q" placeholder="Search articles, authors, or tags…" maxlength="200"><button class="sr-only" type="submit">Search</button></form>' : '<span>Editorial workspace</span>'}</header><div class="connection" role="status" data-connection hidden>You appear to be offline. Keep this page open; reconnect before saving or publishing.</div><main id="content">${process.env.CMS_DEMO_MODE === '1' ? '<p class="notice" role="status"><strong>Local demo — temporary data.</strong> Sign in with demo@example.com / local-demo-only-1234. Personal staff accounts are not connected.</p>' : ''}${notice ? `<p class="notice" role="status">${escape(notice)}</p>` : ''}${body}</main><footer>LyricalSource CMS <span>Built for the people behind the stories.</span></footer></div></div></body></html>`;
  return cmsPath ? html.replace(/(href|src|action)="\/(?!\/)/g, `$1="${cmsPath}/`) : html;
}
module.exports = { escape, layout, cmsUrl };
